parameters:
- name: env
  type: string
  values:
  - dev
  - staging
  - prod
- name: site
  type: string

variables:
- group: common-${{ parameters.env }}-secret
- group: ${{ parameters.site }}-public
- group: ${{ parameters.site }}-${{ parameters.env }}-public
- group: ${{ parameters.site }}-${{ parameters.env }}-secret

jobs:
- deployment: deployResourcesJob
  displayName: 'Deploy Environment Job'
  pool:
    vmImage: ubuntu-20.04
  environment: '$(resourceGroupName)'
  strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self # To force checkout since project resides in github repo.

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy Resources'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(serviceConnectionName)'
              subscriptionId: '$(subscriptionId)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupName)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: 'azure/arm-templates/deploy-resources.json'
              overrideParameters: >-
                -armTemplateRepoRawFilesBaseUrl "$(armTemplateRepoRawFilesBaseUrl)"
                -corporateGatewayIpAddress "$(corporateGatewayIpAddress)"
                -currentProjectRepoRawFilesBaseUrl "$(currentProjectRepoRawFilesBaseUrl)"
                -customApplicationFqdn "$(customApplicationFqdn)"
                -databaseServerAdministratorLogin "$(databaseServerAdminUsername)"
                -databaseServerAdministratorLoginPassword "$(databaseServerAdminPassword)"
                -databaseServerBackupRetentionDays $(databaseServerBackupRetentionDays)
                -databaseServerGeoRedundantBackup "$(databaseServerGeoRedundantBackup)"
                -databaseServerHighAvailabilityMode "$(databaseServerHighAvailabilityMode)"
                -databaseServerSkuName "$(databaseServerSkuName)"
                -databaseServerSkuTier "$(databaseServerSkuTier)"
                -databaseServerStandbyAvailabilityZone "$(databaseServerStandbyAvailabilityZone)"
                -databaseServerStorageSizeGB "$(databaseServerStorageSizeGB)"
                -dataDiskSizeGB $(dataDiskSizeGB)
                -deniedIpAddressList "$(deniedIpAddressList)"
                -environmentName "$(environmentName)"
                -gatewaySslCertificateUri "$(gatewaySslCertificateUri)"
                -gatewayUserAssignedIdentity "$(gatewayUserAssignedIdentity)"
                -genericShellScriptsRepoRawFilesBaseUrl "$(genericShellScriptsRepoRawFilesBaseUrl)"
                -location "$(location)"
                -logAnalyticsWorkspaceRetentionPeriod $(logAnalyticsWorkspaceRetentionPeriod)
                -moodleAdminEmail "$(moodleAdminEmail)"
                -moodleAdminPassword "$(moodleAdminPassword)"
                -moodleAdminUsername "$(moodleAdminUsername)"
                -moodleDatabasePassword "$(moodleDatabasePassword)"
                -moodleDatabaseUsername "$(moodleDatabaseUsername)"
                -moodleUpgradeKey "$(moodleUpgradeKey)"
                -projectShortName "$(projectShortName)"
                -resourceTags $(resourceTags)
                -smtpServerFqdn "$(smtpServerFqdn)"
                -smtpServerFromAddress "$(smtpServerFromAddress)"
                -smtpServerPassword "$(smtpServerPassword)"
                -smtpServerPort $(smtpServerPort)
                -smtpServerUsername "$(smtpServerUsername)"
                -virtualMachineTags $(virtualMachineTags)
                -virtualNetworkAddressBase "$(virtualNetworkAddressBase)"
                -webServerAdminEmail "$(webServerAdminEmail)"
                -webServerAdminPassword "$(webServerAdminPassword)"
                -webServerAdminUsername "$(webServerAdminUsername)"
                -webServerRebootUtcTime "$(webServerRebootUtcTime)"
              deploymentMode: 'Incremental'
              deploymentName: '$(projectShortName)-resources_$(Build.BuildNumber)'

