parameters:
- name: env
  type: string

variables:
- ${{ if eq(parameters.env, 'dev') }}:
  - group: openLearning-moodleSingleNode-dev-clear
- ${{ if eq(parameters.env, 'staging') }}:
  - group: openLearning-moodleSingleNode-staging-clear
- ${{ if eq(parameters.env, 'prod') }}:
  - group: openLearning-moodleSingleNode-prod-clear

jobs:
- deployment: deployResourcesJob
  displayName: 'Deploy Environment Job'
  pool:
    vmImage: ubuntu-20.04
  environment: '$(resourceGroupName)'
  strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self # To force checkout since project resides in github repo.

          - script: |
              pwd
              whoami
              ls -al
              ls -al azure
              ls -al /home/vsts/work/1/s/azure/scripts
              ls -al /home/vsts/work/1/s/azure/scripts/tear_down_environment.sh
              # chmod ugo+x /home/vsts/work/1/s/azure/scripts/tear_down_environment.sh
              # ls -al /home/vsts/work/1/s/azure/scripts/tear_down_environment.sh

          - task: AzureCLI@2
            displayName: 'Tear Down Environment'
            inputs:
              azureSubscription: '$(serviceConnectionName)'
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: 'azure/scripts/tear_down_environment.sh'
              arguments: >-
                --resource-group-name "$(resourceGroupName)"
