#!/bin/bash
# Common tasks that should be run on any VMs prior to customization.
# This script must be run as root (ex.: sudo sh [script_name])
# Style Guide: https://google.github.io/styleguide/shellguide.html

# Parameters (all manadatory)
declare -A parameters=( \
  [server_admin_email]= \
  [server_reboot_utc_time]= \
  [server_name]=)

# Constants
readonly AUTO_UPGRADES_CONF_FILE_PATH=/etc/apt/apt.conf.d/20auto-upgrades
readonly UNATTENDED_UPGRADES_CONF_FILE_PATH=/etc/apt/apt.conf.d/50unattended-upgrades
readonly APTICRON_CONF_FILE_PATH=/etc/apticron/apticron.conf

# Functions
source ./common_functions.sh

function main {
  set_trap

  ###############################################################################
  echo_title "Start of $0"
  ###############################################################################

  ###############################################################################
  echo_title "Parse Input Parameters"
  ###############################################################################
  parse_parameters "$@"

  ###############################################################################
  echo_title "Upgrade server"
  ###############################################################################
  echo_action "Updating server package index files before the upgrade..."
  apt update
  echo_info "Done."

  echo_action "Upgrading all installed server packages to their latest version and apply available security patches..."
  apt upgrade -y
  echo_info "Done."

  ###############################################################################
  echo_title "Setup Unattended-Upgrades and related packages"
  ###############################################################################
  export DEBIAN_FRONTEND=noninteractive
  echo_action "Installing packages..."
  apt install -y \
    apticron \
    unattended-upgrades
  echo_info "Done."

  echo_action "Enabling OS updates..."
  sed -i -e "s|^//\([[:blank:]]*\"\${distro_id}:\${distro_codename}-updates\";\)$|  \1|g" ${UNATTENDED_UPGRADES_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Setting Unattended-Upgrade::Mail parameter..."
  sed -i -e "s|^//\(Unattended-Upgrade::Mail\) .*$|\1 \"${parameters[server_admin_email]}\";|g" ${UNATTENDED_UPGRADES_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Enabling Unattended-Upgrade::Remove-Unused-Kernel-Packages..."
  sed -i -e "s|^//\(Unattended-Upgrade::Remove-Unused-Kernel-Packages\) .*$|\1 \"true\";|g" ${UNATTENDED_UPGRADES_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Enabling Unattended-Upgrade::Remove-Unused-Dependencies..."
  sed -i -e "s|^//\(Unattended-Upgrade::Remove-Unused-Dependencies\) .*$|\1 \"true\";|g" ${UNATTENDED_UPGRADES_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Enabling Unattended-Upgrade::Automatic-Reboot..."
  sed -i -e "s|^//\(Unattended-Upgrade::Automatic-Reboot\) .*$|\1 \"true\";|g" ${UNATTENDED_UPGRADES_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Setting Unattended-Upgrade::Automatic-Reboot-Time..."
  sed -i -e "s|^//\(Unattended-Upgrade::Automatic-Reboot-Time\) .*$|\1 \"${parameters[server_reboot_utc_time]}\";|g" ${UNATTENDED_UPGRADES_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Setting APT::Periodic::Download-Upgradeable-Packages parameter..."
  echo "APT::Periodic::Download-Upgradeable-Packages \"1\";" >> ${AUTO_UPGRADES_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Setting APT::Periodic::AutocleanInterval parameter..."
  echo "APT::Periodic::AutocleanInterval \"7\";" >> ${AUTO_UPGRADES_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Setting Apticron EMAIL parameter..."
  sed -i -e "s/^\(EMAIL=\).*$/\1\"${parameters[server_admin_email]}\"/g" ${APTICRON_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Setting Apticron SYSTEM parameter..."
  sed -i -e "s/^\(SYSTEM=\).*$/\1\"${parameters[server_name]}\"/g" ${APTICRON_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Setting Apticron NOTIFY_HOLDS parameter..."
  sed -i -e "s/^\(NOTIFY_HOLDS=\).*$/\1\"0\"/g" ${APTICRON_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Setting Apticron NOTIFY_NEW parameter..."
  sed -i -e "s/^\(NOTIFY_NEW=\).*$/\1\"0\"/g" ${APTICRON_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Setting Apticron NOTIFY_NO_UPDATES parameter..."
  sed -i -e "s/^\(NOTIFY_NO_UPDATES=\).*$/\1\"1\"/g" ${APTICRON_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Setting Apticron CUSTOM_SUBJECT parameter..."
  sed -i -e "s/^# \(CUSTOM_SUBJECT=\)\"\".*$/\1'[apticron] \$SYSTEM: \$NUM_PACKAGES package update(s)'/g" ${APTICRON_CONF_FILE_PATH}
  echo_info "Done."

  echo_action "Setting Apticron CUSTOM_NO_UPDATES_SUBJECT parameter..."
  sed -i -e "s/^# \(CUSTOM_NO_UPDATES_SUBJECT=\)\"\".*$/\1'[apticron] \$SYSTEM: no updates'/g" ${APTICRON_CONF_FILE_PATH}
  echo_info "Done."

  ###############################################################################
  echo_title "Clean up server"
  ###############################################################################
  echo_action "Removing server packages that are no longer needed."
  apt autoremove -y
  echo_info "Done."

  ###############################################################################
  echo_title "End of $0"
  ###############################################################################

  unset_trap
}

main "$@"
