#!/bin/bash
# Upgrade server and remove unused packages on Ubuntu 18.04.
# This script must be run as root (ex.: sudo sh ./[script_name]) and prior to
# any server customization.
# Style Guide: https://google.github.io/styleguide/shellguide.html

# Functions
source ./common_functions.sh

function main {
  set_trap

  ###############################################################################
  echo_title "Start of $0"
  ###############################################################################

  ###############################################################################
  echo_title "Upgrade server and remove unused packages"
  ###############################################################################
  echo_action "Updating server package index files..."
  apt update
  echo_info "Done."

  echo_action "Upgrading all installed server packages to their latest version and apply available security patches..."
  apt upgrade -y
  echo_info "Done."

  echo_action "Removing server packages that are no longer needed."
  apt autoremove -y
  echo_info "Done."

  ###############################################################################
  echo_title "End of $0"
  ###############################################################################

  unset_trap
}

main "$@"
